/*
    @AUTHOR:    PRAVEEN KUMAR V
    @DESC:      THIS QUERY RETRIEVES HISTORICAL ADJUSTED PRICE FOR A SECURITY
     
    @VER:       V_0.01
      
    @EDITS: 

*/



DECLARE @INDEXLISTINTCODE INT = 4408 -- 4408 S&P 500


SELECT 
--IL.INDEXLISTDESC ,
--CQ.INFOCODE ,
MS.COUNTRY,
MS.ID AS [QAID] ,
MS.SECCODE,
MS.NAME ,
(A.SEDOL+A.SEDOLCHK) AS SEDOL,
MS.TYP AS REGCODE,
DD.MARKETDATE,
CASE WHEN DX.PRICEUNIT = 'E-02' THEN (DD.CLOSE_*DA.CUMADJFACTOR)/100 ELSE DD.CLOSE_*DA.CUMADJFACTOR END AS [CLOSE],
DD.VOLUME

FROM DS2INDEXLIST IL
LEFT JOIN DS2CONSTMTH CM
	ON IL.INDEXLISTINTCODE = CM.INDEXLISTINTCODE
	AND CM.ENDDATE = (SELECT MAX(ENDDATE) FROM DS2CONSTMTH WHERE INDEXLISTINTCODE = CM.INDEXLISTINTCODE)     -- TO GET LATEST SECURITY LIST
LEFT JOIN DS2CTRYQTINFO CQ
	ON CM.INFOCODE = CQ.INFOCODE   -- TO GET THE NAME OF THE SECURITY
LEFT JOIN DS2SEDOLCHG A
	ON CQ.INFOCODE = A.INFOCODE 
	AND A.STARTDATE = (SELECT MAX(STARTDATE) FROM DS2SEDOLCHG WHERE INFOCODE = A.INFOCODE)  -- LATEST SEDOL
LEFT JOIN DS2PRIMQTPRC DD
    ON  DD.INFOCODE = CQ.INFOCODE
    AND DD.MARKETDATE < (SELECT CONVERT(DATE,SWITCHOFFSET(CONVERT(DATETIMEOFFSET,GETUTCDATE()),'+05:30')))
LEFT JOIN DS2ADJ DA
    ON  DA.INFOCODE = DD.INFOCODE
    AND DA.ADJTYPE = 2
    AND DD.MARKETDATE BETWEEN DA.ADJDATE AND COALESCE(DA.ENDADJDATE,'2079-01-01')
LEFT JOIN DS2EXCHQTINFO DX
    ON  DX.INFOCODE = DD.INFOCODE
    AND DX.EXCHINTCODE = DD.EXCHINTCODE
LEFT JOIN (SELECT *,1 AS 'TYP' FROM SECMAPX UNION SELECT *,6 AS 'TYP' FROM GSECMAPX) AS MA	-- TO MAP WITH MASTER TABLES (SECCODE)
	ON MA.VENCODE = CQ.INFOCODE
	AND MA.VENTYPE = '33'          -- DATASTREAM MAPPING
LEFT JOIN (SELECT *, 1 AS 'TYP' FROM SECMSTRX UNION SELECT *, 6 AS 'TYP' FROM GSECMSTRX) AS MS
	ON MS.SECCODE = MA.SECCODE
	AND MS.TYP = MA.TYP
	AND MS.TYPE_ = 1 -- EQUITY

WHERE IL.INDEXLISTINTCODE = @INDEXLISTINTCODE
ORDER BY MS.NAME