/*
    @AUTHOR:     PRAVEEN KUMAR V
    @DESC:       THIS QUERY RETURNS THE NEXT EPS EXPECTED REPORT DATES FOR UP TO TWO QUARTERLY PERIODS IN THE FUTURE AS CALUCLATED BY QFS ALGORITHM.
 
 
    @EDITS:      4/17/2018: UPDATED QUERY TO USE LATEST MAPPING LOGIC CONSISTENT WITH OTHER FACTOR QUERIES.
                 5/24/2018: CHANGED THE DESCRIPTION FROM COMPANY REPORTED TO QFS CALCULATED.
                 5/26/2018: PACING AND ADDED COUNTRY OF EXCHANGE

*/
 
WITH IBESV1MAPPING AS (
    SELECT *,1 AS REGCODE FROM SECMAPX WHERE VENTYPE = 42 
        UNION ALL 
    SELECT *,6 AS REGCODE FROM GSECMAPX WHERE VENTYPE = 2
)

SELECT
      U.COUNTRYOFEXCHANGE
    , U.ID 
    , U.SECCODE
    , U.REGCODE
    , U.EXCHANGE 
    , I.ITICKER
    , I.CODE 
    , X.MEASURE 
    , X.Q1ENDDATE 
    , X.Q1RPTDATE 
    , X.Q2ENDDATE 
    , X.Q2RPTDATE
FROM SUPPORT_DB.DBO.UNIVERSE U
JOIN IBESV1MAPPING P
    ON  P.SECCODE = U.SECCODE
    AND P.REGCODE = U.REGCODE
    AND P.EXCHANGE = U.EXCHANGE
    AND P.[RANK] = (SELECT MIN([RANK]) FROM IBESV1MAPPING WHERE SECCODE = P.SECCODE AND REGCODE = P.REGCODE AND EXCHANGE = P.EXCHANGE)
JOIN (SELECT *,1 AS REGCODE FROM IBESINFO3 UNION ALL SELECT *,6 AS REGCODE FROM IBGSINFO3) I
    ON  I.CODE = P.VENCODE
    AND I.REGCODE = CASE P.EXCHANGE WHEN 1 THEN 1 WHEN 2 THEN 6 WHEN 0 THEN 6 END
---- QFS CALCULATED REPORT DATES
JOIN (SELECT *,1 AS REGCODE FROM IBQEXDT UNION ALL SELECT *,6 AS REGCODE FROM IBGQEXDT) X
    ON  X.CODE = I.CODE
    AND X.REGCODE = I.REGCODE
WHERE U.COUNTRYOFEXCHANGE IN ('United Kingdom') --@COUNTRIES
-- ORDER BY ID